# Generated by Django 4.1 on 2022-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Itemtodolist',
        ),
    ]
